# Generated by Django 5.1.13 on 2025-10-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
